trigger : none 
pool    : 5Jan26agent
stages:
  - stage: 
    displayName: terraformtool
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
        
