trigger : none 
pool    : 5Jan26agent
stages:
  - stage: 
    displayName: terraformtool
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
        - task: TerraformTask@5
          inputs: 
            provider: 'azurerm'
            command: 'init'
            backendAzureRmOverrideSubscriptionID: '0a2d6fb2-0cdf-4ef1-bc96-b60d4c91cfb4'
            backendAzureRmStorageAccountName: 'storageaccount5jan26'
            backendAzureRmContainerName: 'jancon'
            backendAzureRmKey: 'jankey'
        
